# Spoonshare
# Development docker-compose
# Variables are in .env - follow .env.example to create locally

version: "3.8"

networks:
  application:
  data:

volumes:
  pgdata:

services:
  ui:
    build:
      context: ./ui
    depends_on:
      - api
    image: ${PROJECT_NAME}_ui
    networks:
      - application
    ports:
      - "5173:5173"
    stdin_open: true
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
  api:
    build:
      context: ./api
    depends_on:
      - db
    image: ${PROJECT_NAME}_api
    networks:
      - application
      - data
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./api:/app

  db:
    image: postgres:15.1-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - data
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/support/postgres/db_init.sh:/docker-entrypoint-initdb.d/initializer.sh
