# Spoonshare
# Development docker-compose
version: "3.8"
services:
  ui:
    image:
    ports:
    networks:
    configs:
    secrets:
  api:
    image:
    volumes:
    networks:

  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: spoonshare
      POSTRESS_PASSWORD: password
    volumes:
      - pgdata: /var/lib/postgresql/data

volumes:
  db:
    driver: local
    driver_opts:

configs:
  httpd-config:
    external:

secrets:
  server-certificate:
    external:

networks:
  front-tier:
  back-tier: